server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Sirve todos los archivos estáticos directamente
    location /assets/ {
        try_files $uri =404;
    }

    location /logos/ {
        try_files $uri =404;
    }

    location /vite.svg {
        try_files $uri =404;
    }

    # Redirige cualquier otra ruta de la SPA a index.html
    location / {
        try_files $uri /index.html;
    }

    # Optional: Evitar logs innecesarios
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
}
